name = "appfactory-website"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
pages_build_output_dir = "out"

[vars]
CONTACT_TO_EMAIL = "suport@xuzhen.top"
CONTACT_FROM_EMAIL = "noreply@xuzhen.top"

[env.production]
name = "appfactory-website"
